apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-pipelines-agent
spec:
  template:
    spec:
      containers:
        - name: data-pipelines-agent
          env:
            - name: PREFECT_POOL
              value: dev-agent-pool
