apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - ./dev

namespace: data-pipelines

secretGenerator:
  - name: data-pipelines-secrets
    env: secret.properties

