name: Continuous Integration

on: [push, pull_request]

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      - name: flake8 Lint
        uses: py-actions/flake8@v1
        with:
          max-line-length: "140"
          path: "flows"
  validate-k8s:
    runs-on: ubuntu-latest
    name: Validate k8s manifests
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize-version: "4.5.4"
      - name: Write secrets file
        run: $GITHUB_WORKSPACE/scripts/properties_from_env.sh PREFECT_API_KEY PREFECT_API_URL > $GITHUB_WORKSPACE/agent/k8s/secret.properties
      - name: Kustomize
        run: kustomize build agent/k8s > /tmp/kustomized.yaml
      - uses: azure/k8s-lint@v1
        with:
          manifests: |
            /tmp/kustomized.yaml
